# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "appserver" do |appserver|
    appserver.vm.hostname = "appserver"
    appserver.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "dbserver" do |dbserver|
    dbserver.vm.hostname = "dbserver"
    dbserver.vm.network "private_network", type: "dhcp"
  end

  config.vm.provider :virtualbox do |v, override|
    override.vm.box = "bento/ubuntu-18.04"
  end

  config.vm.provider :digital_ocean do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_ed25519'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    override.vm.allowed_synced_folder_types = :rsync
    
    provider.token = ENV['DO_TOKEN']
    provider.ssh_key_name = 
    provider.image = 'ubuntu-18-04-x64'
    provider.region = 'nyc1'
    provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    sudo apt-get -qq update
    sudo apt-get install -y puppet-agent
  SHELL

  config.puppet_install.puppet_version = :latest
  config.vm.provision :puppet do |puppet|
    puppet.environment_path = "environments/"
    puppet.environment = "test"
  end


end
