# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"


  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    sudo apt-get -qq update
    sudo apt-get install -y puppet-agent
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "environments/"
    puppet.environment = "test"
  end
end
